Models/Ticket.cs
using System.ComponentModel.DataAnnotations;

namespace TheIssueTracker.Models
{
    public class Ticket
    {
        public int Id { get; set; }

        [Required]
        [StringLength(300, ErrorMessage = "The {0} must be at least {2} and max {1} characters long.", MinimumLength = 2)]
        public string? Title { get; set; }

        [Required]
        public string? Description { get; set; }

        [DataType(DataType.DateTime)]
        [Display(Name = "Created Date")]
        public DateTime Created { get; set; }

        [DataType(DataType.DateTime)]
        [Display(Name = "Updated Date")]
        public DateTime? Updated { get; set; }

        public bool Archived { get; set; }

        [Display(Name = "Archived by Project")]
        public bool ArchivedByProject { get; set; }

        public int ProjectId { get; set; }
        public int TicketTypeId { get; set; }
        public int TicketStatusId { get; set; }
        public int TicketPriorityId { get; set; }
        public string? DeveloperUserId { get; set; }

        [Required]
        public string? SubmitterUserId { get; set; }

        //Navigation Properties
        public virtual Project? Project { get; set; }
        public virtual TicketPriority? TicketPriority { get; set; } 
        public virtual TicketType? TicketType { get; set; }
        public virtual TicketStatus? TicketStatus { get; set; }

        public virtual BTUser? SubmitterUser { get; set; }
        public virtual BTUser? DeveloperUser { get; set; }

        public virtual ICollection<TicketComment> TicketComments { get; set; } = new HashSet<TicketComment>();
        public virtual ICollection<TicketAttachment> TicketAttachments { get; set; } = new HashSet<TicketAttachment>();
        public virtual ICollection<TicketHistory> TicketHistories { get; set; } = new HashSet<TicketHistory>();
    }
}

Models/TicketType.cs
namespace TheIssueTracker.Models
{
    public class TicketType
    {
        public int Id { get; set; }
        public string? Name { get; set; }
    }
}

Models/ViewModels/AssignDeveloperViewModel.cs
using Microsoft.AspNetCore.Mvc.Rendering;

namespace TheIssueTracker.Models.ViewModels
{
    public class AssignDeveloperViewModel
    {
        public Ticket? Ticket { get; set; }
        public SelectList? DeveloperList { get; set; }
        public string? DeveloperId { get; set; }
    }


}

Controllers/TicketsController.cs
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel.Design;
using System.Linq;
using System.Net.Sockets;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using TheIssueTracker.Data;
using TheIssueTracker.Extensions;
using TheIssueTracker.Models;
using TheIssueTracker.Models.Enums;
using TheIssueTracker.Models.ViewModels;
using TheIssueTracker.Services;
using TheIssueTracker.Services.Interfaces;
using Org.BouncyCastle.Bcpg;

namespace TheIssueTracker.Controllers
{
    [Authorize]
    public class TicketsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<BTUser> _userManager;
        private readonly IBTProjectService _projectService;
        private readonly IBTTicketService _ticketService;
        private readonly IBTRolesService _rolesService;
        private readonly IBTFileService _fileService;
        private readonly IBTTicketHistoryService _ticketHistoryService;


        public TicketsController(ApplicationDbContext context, 
                                 UserManager<BTUser> userManager,
                                 IBTProjectService projectService, 
                                 IBTTicketService ticketService, 
                                 IBTRolesService rolesService, 
                                 IBTFileService fileService, 
                                 IBTTicketHistoryService ticketHistoryService)
        {
            _context = context;
            _userManager = userManager;
            _projectService = projectService;
            _ticketService = ticketService;
            _rolesService = rolesService;
            _fileService = fileService;
            _ticketHistoryService = ticketHistoryService;
        }

        // GET: Tickets
        public async Task<IActionResult> Index()

        {
	
			int companyId = User.Identity!.GetCompanyId();

            List<Ticket> tickets = await _ticketService.GetTicketsByCompanyIdAsync(companyId);

			ViewData["ProjectId"] = new SelectList(_context.Projects, "Id", "Description"/*, ticket.ProjectId*/);
            ViewData["TicketPriorityId"] = new SelectList(await _ticketService.GetTicketPriorities(), "Id", "Name");
            ViewData["TicketStatusId"] = new SelectList(await _ticketService.GetTicketStatuses(), "Id", "Name");
            ViewData["TicketTypeId"] = new SelectList(await _ticketService.GetTicketTypes(), "Id", "Name");

            return View(tickets);
        }

        // GET: Tickets/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Tickets == null)
            {
                return NotFound();
            }

            Ticket? ticket = await _ticketService.GetTicketByIdAsync(id.Value, User.Identity!.GetCompanyId());
           
            if (ticket == null)
            {
                return NotFound();
            }

            return View(ticket);
        }

		public async Task<IActionResult> DetailsCopy(int? id)
		{
			if (id == null || _context.Tickets == null)
			{
				return NotFound();
			}

			Ticket? ticket = await _ticketService.GetTicketByIdAsync(id.Value, User.Identity!.GetCompanyId());

			if (ticket == null)
			{
				return NotFound();
			}

			return View(ticket);
		}

		// GET: Tickets/Create
		[HttpGet]
        public async Task<IActionResult> Create()
        {           

            List<Project> projects = await _projectService.GetAllProjectsByCompanyIdAsync(User.Identity!.GetCompanyId());
			List<TicketPriority> priorities = await _ticketService.GetTicketPriorities();
			List<TicketType> types = await _ticketService.GetTicketTypes();
            List<TicketStatus> statuses = await _ticketService.GetTicketStatuses();

			ViewData["ProjectId"] = new SelectList(projects, "Id", "Name");
            ViewData["TicketPriorityId"] = new SelectList(priorities, "Id", "Name");
            ViewData["TicketStatusId"] = new SelectList(types, "Id", "Name");
            ViewData["TicketTypeId"] = new SelectList(statuses, "Id", "Name");
            
            return View();
        }

        // POST: Tickets/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Title,Description,ProjectId,TicketTypeId,TicketStatusId,TicketPriorityId,DeveloperUserId")] Ticket newTicket)
        {

            ModelState.Remove(nameof(Ticket.SubmitterUserId));

            if (ModelState.IsValid)
            {
                int companyId = User.Identity!.GetCompanyId();

                newTicket.Created = DateTime.UtcNow;
                newTicket.SubmitterUserId = _userManager.GetUserId(User);

                await _ticketService.AddTicketAsync(newTicket);

                await _ticketHistoryService.AddHistoryAsync(null, newTicket, _userManager.GetUserId(User)!);

                return RedirectToAction(nameof(Index));
            }


            List<Project> projects = await _projectService.GetAllProjectsByCompanyIdAsync(User.Identity!.GetCompanyId());

            ViewData["ProjectId"] = new SelectList(projects, "Id", "Name");
            ViewData["TicketPriorityId"] = new SelectList(await _ticketService.GetTicketPriorities(), "Id", "Name");
            ViewData["TicketStatusId"] = new SelectList(await _ticketService.GetTicketStatuses(), "Id", "Name");
            ViewData["TicketTypeId"] = new SelectList(await _ticketService.GetTicketTypes(), "Id", "Name");
            return View(newTicket);
        }

        [HttpGet]
        [Authorize(Roles = $"{nameof(BTRoles.Admin)}, {nameof(BTRoles.ProjectManager)}")]
        public async Task<IActionResult> AssignDeveloper(int? id)
        {
            if (id is null or 0)
            {
                return NotFound();
            }

            Ticket? ticket = await _ticketService.GetTicketByIdAsync(id.Value, User.Identity!.GetCompanyId());

            if (ticket is null)
            {
                return NotFound();
            }

            List<BTUser> developers = await _rolesService.GetUsersInRoleAsync(nameof(BTRoles.Developer), User.Identity!.GetCompanyId());

            BTUser? currentDeveloper = await _ticketService.GetDeveloperAsync(id.Value, User.Identity!.GetCompanyId());

            AssignDeveloperViewModel viewModel = new AssignDeveloperViewModel()
            {
                Ticket = ticket,
                DeveloperId = currentDeveloper?.Id,
                DeveloperList = new SelectList(developers, "Id", "FullName", currentDeveloper?.Id)

            };

            return View(viewModel);
        }

        [HttpPost]
        [Authorize(Roles = $"{nameof(BTRoles.Admin)}, {nameof(BTRoles.ProjectManager)}")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AssignDeveloper(AssignDeveloperViewModel viewModel)
        {

			if (viewModel.Ticket?.Id is not null)
			{
				Ticket? ticket = await _ticketService.GetTicketByIdAsync(viewModel.Ticket.Id, User.Identity!.GetCompanyId());
				if (ticket is not null)
				{
					ticket.DeveloperUserId = viewModel.DeveloperId;

					await _ticketService.UpdateTicketAsync(ticket, User.Identity!.GetCompanyId());

                  
					return RedirectToAction(nameof(Details), new { id = viewModel.Ticket!.Id });
				}
			}

			return BadRequest();
		}

        // GET: Tickets/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var ticket = await _ticketService.GetTicketByIdAsync(id.Value, User.Identity!.GetCompanyId());
            if (ticket == null)
            {
                return NotFound();
            }

            var priorities = await _ticketService.GetTicketPriorities();
            var statuses = await _ticketService.GetTicketStatuses();
            var types = await _ticketService.GetTicketTypes();

            ViewData["TicketPriorityId"] = new SelectList(priorities, "Id", "Name");
            ViewData["TicketStatusId"] = new SelectList(statuses, "Id", "Name");
            ViewData["TicketTypeId"] = new SelectList(types, "Id", "Name");
            
            return View(ticket);
        }

        // POST: Tickets/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Title,Description,Created,Updated,Archived,ArchivedByProject,ProjectId,TicketTypeId,TicketStatusId,TicketPriorityId,DeveloperUserId,SubmitterUserId")] Ticket ticket)
        {
            if (id != ticket.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    Ticket? oldTicket = await _ticketService.GetTicketAsNoTrackingAsync(ticket.Id, User.Identity!.GetCompanyId());
                    ticket.Created = DateTime.UtcNow;

                    await _ticketService.UpdateTicketAsync(ticket, User.Identity!.GetCompanyId());
                    ticket = (await _ticketService.GetTicketByIdAsync(ticket.Id, User.Identity!.GetCompanyId()))!;

                    await _ticketHistoryService.AddHistoryAsync(oldTicket, ticket, _userManager.GetUserId(User)!);
                }
                catch (DbUpdateConcurrencyException)
                {
                    throw;
                }

Views/Tickets/ArchivedTickets.cshtml
@model IEnumerable<TheIssueTracker.Models.Ticket>

@{
	ViewData["Title"] = "Index";
}

<div class="row">
	<h2 class="m-t-0 h3"><b>Archived Tickets </b></h2>
</div>
<div class="row">
	<div class="col-12">
		<div class="card">
			<div class="card-body">

				<table id="datatable" class="table table-bordered dt-responsive table-responsive nowrap">
					<thead>
						<tr>
							<th>Title</th>
							<th>ID</th>
							<th>Description</th>
							<th>Last Updated</th>
							<th>Project</th>
							<th>Archived By Project</th>
							<th>Priority</th>
							<th>Type</th>
							<th>&nbsp;</th>
						</tr>
					</thead>

					<tbody>
						@foreach (Ticket ticket in Model)
						{
							<tr>
								<td>
									<a asp-controller="Tickets" asp-action="Details" asp-route-id="@ticket.Id">@ticket.Title</a>
								</td>
								<td>@ticket.Id</td>
								<td>@ticket.Description</td>
								<td>@ticket.Updated</td>
								<td>
									<a asp-controller="Projects" asp-action="Details" asp-route-id="@ticket.Project.Id">@ticket.Project!.Name</a>
								</td>
								<td>@ticket.ArchivedByProject</td>
								<td>
									@if (ticket.TicketPriority!.Name == "Urgent")
									{
										<h5 style="color:firebrick">Urgent</h5>
									}
									else if (ticket.TicketPriority!.Name == "High")
									{
										<h5 style="color:orangered">High</h5>

									}
									else if (ticket.TicketPriority!.Name == "Medium")
									{
										<h5 style="color:darkslateblue">Medium</h5>
									}
									else if (ticket.TicketPriority!.Name == "Low")
									{
										<h5 style="color:forestgreen">Low</h5>
									}

								</td>
								<td>
									@if (ticket.TicketType!.Name == "NewDevelopment")
									{
										<h5 class="badge bg-soft-success">New Development</h5>
									}
									else if (ticket.TicketType!.Name == "WorkTask")
									{
										<h5 class="badge bg-soft-pink">Work Task</h5>
									}
									else if (ticket.TicketType!.Name == "Defect")
									{
										<h5 class="badge bg-soft-danger">Defect</h5>
									}
									else if (ticket.TicketType!.Name == "ChangeRequest")
									{
										<h5 class="badge bg-soft-info">Change Request</h5>
									}
									else if (ticket.TicketType!.Name == "Enhancement")
									{
										<h5 class="badge bg-soft-primary">Enhancement</h5>
									}
									else if (ticket.TicketType!.Name == "GeneralTask")
									{
										<h5 class="badge bg-soft-light">General Task</h5>
									}
								</td>
								<td class="d-flex justify-content-evenly">
									<a asp-action="Restore" asp-controller="Tickets" asp-route-id="@ticket.Id" type="button" class="btn btn-soft-success waves-effect waves-light">Restore</a>
								</td>
							</tr>
						}
					</tbody>
				</table>
			</div>
		</div>

	</div>
</div> <!-- end row -->
@section Scripts{
	<script>
		$('#datatable').DataTable();
	</script>
}

Views/Tickets/Details.cshtml
@model TheIssueTracker.Models.Ticket

@using TheIssueTracker.Models.Enums;
@using TheIssueTracker.Services;
@using TheIssueTracker.Services.Interfaces;
@inject IBTFileService _FileService;
@inject IBTRolesService _RolesService;

@{
	ViewData["Title"] = "Details";
}

<div class="row">
	<div class="col-md-8">
		<div class="card">
			<div class="card-body task-detail">
				<div class="dropdown float-end">
					<a href="#" class="dropdown-toggle arrow-none card-drop" data-bs-toggle="dropdown" aria-expanded="false">
						<i class="mdi mdi-dots-vertical"></i>
					</a>
					<div class="dropdown-menu dropdown-menu-end">
						<!-- item-->
						<a asp-controller="Tickets" asp-action="Edit" asp-route-id="@Model.Id" data-bs-toggle="modal" data-bs-target="#TicketsEdit" class="dropdown-item">Edit</a>
						<!-- item-->
						<a asp-controller="Tickets" asp-action="Archive" asp-route-id="@Model.Id" class="dropdown-item">Archive</a>
						<!-- item-->
						<a asp-controller="Projects" asp-action="Details" asp-route-id="@Model.Project!.Id" class="dropdown-item">View Project Details</a>

					</div>
				</div>
				<div class="d-flex mb-3">
					<img class="flex-shrink-0 me-3 rounded-circle avatar-md" alt="64x64" src="@_FileService.ConvertByteArrayToFile(Model.SubmitterUser!.ImageFileData,Model.SubmitterUser.ImageFileType,DefaultImage.BTUserImage)">
					<div class="flex-grow-1">
						<h3 class="media-heading mt-0">@Model.Title</h3>
						<span>
							@if (Model.TicketStatus!.Name == "New")
							{
								<h5 class="badge bg-success">New Ticket</h5>
							}
							else if (Model.TicketStatus!.Name == "Development")
							{
								<h5 class="badge bg-info">In Development</h5>
							}
							else if (Model.TicketStatus!.Name == "Testing")
							{
								<h5 class="badge bg-warning">In Testing</h5>
							}
							else if (Model.TicketStatus!.Name == "Resolved")
							{
								<h5 class="badge bg-secondary">Resolved</h5>
							}
						</span>
					</div>
				</div>
				<p>
					@Model.Description
				</p>


				<div class="row task-dates mb-0 mt-2">
					<div class="col-lg-6">
						<h5 class="font-600 m-b-5">Start Date</h5>
						<p> @Model.Created.ToString("MM.dd.yyyy") <small class="text-muted">@Model.Created.ToString("HH:mm")</small></p>
					</div>

					<div class="col-lg-6">
						<h5 class="font-600 m-b-5">Project Status: </h5>
						@if (Model.Project.Archived)
						{
							<h5 class="badge bg-secondary">Archived</h5>
						}
						else if (DateTime.UtcNow.Date > DateTime.SpecifyKind(Model.Project.EndDate, DateTimeKind.Utc).Date)
						{
							<h3 class="btn btn-danger">Overdue</h3>
						}
						else
						{
							<h5 class="badge bg-warning">In Progress</h5>
						}
						@*<p> @Model.Project.EndDate.ToString("MM.dd.yyyy") <small class="text-muted">@Model.Project.EndDate.ToString("HH:mm")</small></p>*@
					</div>
				</div>

				<h5 class="text-muted">Submitter:</h5>
				<h4>@Model.SubmitterUser!.FullName</h4>
				<br />

				@if (Model.DeveloperUserId is not null)
				{
					<h5 class="text-muted">Developer:</h5>
					<h4>@Model.DeveloperUser!.FullName</h4>
				}
				else if (Model.DeveloperUserId is null)
				{
					<div>
						<a asp-action="AssignDeveloper" asp-controller="Tickets" asp-route-id="@Model.Id" type="button" class="btn btn-soft-warning waves-effect waves-light">Assign Developer</a>
						@*@foreach (BTUser user in (await _RolesService.GetUsersInRoleAsync("Developer", Model.Project.CompanyId)))
					{

					<a> <img class="rounded-circle avatar-sm" alt="64x64" src="@_FileService.ConvertByteArrayToFile(Model.SubmitterUser.ImageFileData,Model.SubmitterUser.ImageFileType,DefaultImage.BTUserImage)"> </a>

					}
					<a href="#"><span class="add-new-plus"><i class="mdi mdi-plus"></i> </span></a>*@
					</div>
				}
				<hr />
				<div class="clearfix"></div>

				@*Ticket Attachments*@
				<div class="row clearfix">
					<div>
						<form asp-action="AddTicketAttachment" asp-controller="Tickets" enctype="multipart/form-data" method="post">
							<div asp-validation-summary="ModelOnly" class="text-danger"></div>
							<input type="hidden" asp-for="@Model.Id" name="TicketId">
							<div class="media-body ml-3">
								<label>

									<h5 class="text-muted">File Description:</h5>
									<input asp-for="@Model.TicketAttachments.FirstOrDefault()!.Description" type="text" class="form-control" />
								</label><br />
								<label class="btn btn-outline-primary btn-sm">
									<input asp-for="@Model.TicketAttachments.FirstOrDefault()!.FormFile" type="file" class="form-control-file" />
								</label>
								<button type="submit" class="btn btn-outline-secondary btn-sm md-btn-flat">Submit</button>
							</div>
						</form>
					</div>
				</div>

				@* Ticket attachments part 2 here *@

				<hr />
				<h6>Attachments</h6>
				<div class="container">
					<div class="row">
						@foreach (TicketAttachment item in Model.TicketAttachments)
						{
							<div class="col col-sm-2">
								<a asp-action="ShowFile" asp-controller="Tickets" asp-route-Id="@item.Id">
									<div class="icon">
										<img src="@_FileService.GetFileIcon(item.Description!)" style="height:50px;width:50px" data-bs-toggle="tooltip" data-bs-placement="top" title="" data-bs-original-title="@item.Description" />
									</div>
								</a>
								<div style="font-size:x-small">
									<div class="file-name">
										<strong>@item.Description</strong>
									</div>
									<small>Size: @_FileService.FormatFileSize(item.FileData!.Length) </small>
								</div>
							</div>
						}
					</div>
				</div>


				@*<div class="attached-files mt-3">
				<h5>Attached Files </h5>
				<ul class="list-inline files-list">
				<li class="list-inline-item file-box">
				<a href=""><img src="assets/images/attached-files/img-1.jpg" class="img-fluid img-thumbnail" alt="attached-img" width="80"></a>
				<p class="font-13 mb-1 text-muted"><small>File one</small></p>
				</li>
				<li class="list-inline-item file-box">
				<a href=""><img src="assets/images/attached-files/img-2.jpg" class="img-fluid img-thumbnail" alt="attached-img" width="80"></a>
				<p class="font-13 mb-1 text-muted"><small>Attached-2</small></p>
				</li>
				<li class="list-inline-item file-box">
				<a href=""><img src="assets/images/attached-files/img-3.jpg" class="img-fluid img-thumbnail" alt="attached-img" width="80"></a>
				<p class="font-13 mb-1 text-muted"><small>Dribbble shot</small></p>
				</li>
				<li class="list-inline-item file-box ms-2">
				<div class="fileupload add-new-plus">
				<span><i class="mdi-plus mdi"></i>Add file(s)</span>
				<input type="file" class="upload">
				</div>
				</li>
				</ul>
				</div>*@

			</div>
		</div>

	</div><!-- end col -->

	<div class="col-md-4">
		<div class="card">
			<div class="card-body">

				<h4 class="header-title mt-0 mb-3">Comments (@Model.TicketComments.Count)</h4>

				<div>
					@*Loop to show comments made for the Ticket*@
					@foreach (TicketComment comment in Model.TicketComments)
					{
						<li>
							<div class="d-flex mb-3">
								<div class="flex-shrink-0 me-3">
									<a><img class="rounded-circle avatar-sm" alt="64x64" src="@_FileService.ConvertByteArrayToFile(comment.User!.ImageFileData,comment.User!.ImageFileType,DefaultImage.BTUserImage)"></a>
								</div>
								<div class="flex-grow-1">
									<h5 class="mt-0">@comment.User!.FullName</h5><span>@comment.Created.ToString("MM.dd.yy")  <small class="text-muted">@comment.Created.ToString("HH:mm")</small></span>
									<p class="font-13 mb-0">
										@comment.Comment
									</p>
								</div>
							</div>

						</li>
					}


					<div class="d-flex mb-3">
						<div class=" me-3">
							<a href="#"> <img class="rounded-circle avatar-sm" alt="64x64" src="@_FileService.ConvertByteArrayToFile(Model.SubmitterUser.ImageFileData,Model.SubmitterUser.ImageFileType,DefaultImage.BTUserImage)"> </a>
						</div>
						<form asp-action="AddTicketComment" asp-controller="Tickets" enctype="multipart/form-data" method="post" class="flex-grow-1">
							<div asp-validation-summary="ModelOnly" class="text-danger"></div>
							<input type="hidden" asp-for="@Model.Id" name="TicketId">
							<input type="text" name="comment" class="form-control" placeholder="Add a comment...">
							<div class="form-group mt-2">
								<input type="submit" value="Add" class="btn btn-primary rounded-pill" />
							</div>
						</form>
					</div>

				</div>
			</div>
		</div>

	</div><!-- end col -->
</div>

<!-- Modal -->
@*Edit Tickets Modal*@
<div class="modal fade" id="TicketsEdit" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<h4 class="modal-title" id="staticBackdropLabel">Edit Ticket</h4>
				<button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
			</div>
			<div class="modal-body">
				<form asp-action="Edit" asp-controller="Tickets" method="post">
					<input type="hidden" asp-for="@Model.Id" />
					<input type="hidden" asp-for="@Model.Created" />
					<input type="hidden" asp-for="@Model.SubmitterUserId" />
					<input type="hidden" asp-for="@Model.DeveloperUserId" />
					<input type="hidden" asp-for="@Model.ProjectId" />
					<input type="hidden" asp-for="@Model.Archived" />
					<input type="hidden" asp-for="@Model.ArchivedByProject" />
					<div class="row g-3 p-2">
						<div class="col-12 d-flex justify-content-center">
							<div class="row">
								<div class="col-12">
									<label asp-for="@Model.Title" class="control-label"></label>
									<input asp-for="@Model.Title" class="form-control" />
									<span asp-validation-for="@Model.Title" class="text-danger"></span>
								</div>
								<div class="col-12">
									<label asp-for="@Model.Description" class="control-label"></label>
									<input asp-for="@Model.Description" class="form-control" />
									<span asp-validation-for="@Model.Description" class="text-danger"></span>
								</div>
								<div class="col-12 mt-2">
									<label asp-for="@Model.TicketTypeId" class="control-label"></label>
									<select asp-for="@Model.TicketTypeId" class="form-control" asp-items="@ViewBag.TicketTypeId"></select>
									<span asp-validation-for="@Model.TicketTypeId" class="text-danger"></span>
								</div>
								<div class="col-12 mt-2">
									<label asp-for="@Model.TicketStatusId" class="control-label"></label>
									<select asp-for="@Model.TicketStatusId" class="form-control" asp-items="@ViewBag.TicketStatusId"></select>
									<span asp-validation-for="@Model.TicketStatusId" class="text-danger"></span>
								</div>
								<div class="col-12 mt-2">
									<label asp-for="@Model.TicketPriorityId" class="control-label"></label>
									<select asp-for="@Model.TicketPriorityId" class="form-control" asp-items="@ViewBag.TicketPriorityId"></select>
									<span asp-validation-for="@Model.TicketPriorityId" class="text-danger"></span>
								</div>
								<div class="col-12 d-flex justify-content-center mt-2">
									<button type="submit" class="btn btn-lg btn-primary rounded-pill">Save</button>
								</div>
							</div>
						</div>
					</div>
				</form>

			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>

			</div>
		</div>
	</div>
</div>