Models/Project.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace TheIssueTracker.Models
{
    public class Project
    {
        public int Id { get; set; }
        public int CompanyId { get; set; }

        [Required]
        public string? Name { get; set; }

        [Required]
        public string? Description { get; set; }

        [DataType(DataType.DateTime)]
        [Display(Name = "Created Date")]
        public DateTime Created { get; set; }

        [DataType(DataType.DateTime)]
        [Display(Name = "Start Date")]
        public DateTime StartDate { get; set; }

        [DataType(DataType.DateTime)]
        [Display(Name = "End Date")]
        public DateTime EndDate { get; set; }

        public int ProjectPriorityId { get; set; }

        //Image Properties
        [NotMapped]
        public virtual IFormFile? ImageFormFile { get; set; }
        public byte[]? ImageFileData { get; set; }
        public string? ImageFileType { get; set; }

        public bool Archived { get; set; }

        //Navigation Properties
        public virtual Company? Company { get; set; }
        public virtual ProjectPriority? ProjectPriority { get; set; }
        public virtual ICollection<BTUser> Members { get; set; } = new HashSet<BTUser>();
        public virtual ICollection<Ticket> Tickets { get; set; } = new HashSet<Ticket>();
    }
}

Models/ViewModels/AssignPMViewModel.cs
using Microsoft.AspNetCore.Mvc.Rendering;

namespace TheIssueTracker.Models.ViewModels
{
    public class AssignPMViewModel
    {
        public Project? Project { get; set; }
        public SelectList? PMList { get; set; }
        public string? PMId { get; set; }
    }
}

Models/ViewModels/AssignProjectMembersViewModel.cs
using Microsoft.AspNetCore.Mvc.Rendering;

namespace TheIssueTracker.Models.ViewModels
{
    public class AssignProjectMembersViewModel
    {
        public Project? Project { get; set; }
        public SelectList? UnassignedList { get; set; }
        public SelectList? CurrentList { get; set; }
        public string? MemberId { get; set; }
    }
}

Controllers/ProjectsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using TheIssueTracker.Data;
using TheIssueTracker.Extensions;
using TheIssueTracker.Models;
using TheIssueTracker.Models.Enums;
using TheIssueTracker.Models.ViewModels;
using TheIssueTracker.Services;
using TheIssueTracker.Services.Interfaces;

namespace TheIssueTracker.Controllers
{
    [Authorize]
    public class ProjectsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<BTUser> _userManager;
        private readonly IBTFileService _fileService;
        private readonly IBTProjectService _projectService;
        private readonly IBTTicketService _ticketService;
        private readonly IBTRolesService _rolesService;
        private readonly IBTCompanyService _companyService;

        public ProjectsController(ApplicationDbContext context, UserManager<BTUser> userManager, IBTFileService fileService, IBTProjectService projectService, IBTTicketService ticketService, IBTRolesService rolesService, IBTCompanyService companyService)
        {
            _context = context;
            _userManager = userManager;
            _fileService = fileService;
            _projectService = projectService;
            _ticketService = ticketService;
            _rolesService = rolesService;
            _companyService = companyService;
        }

        // GET: Projects
        public async Task<IActionResult> Index()
        {
  
            List<Project> projects = await _projectService.GetAllProjectsByCompanyIdAsync(User.Identity!.GetCompanyId());

			List<ProjectPriority> priorities = await _projectService.GetProjectPrioritiesAsync();
			ViewData["ProjectPriorityId"] = new SelectList(priorities, "Id", "Name");

			return View(projects);
        }

		public async Task<IActionResult> IndexCopy()
		{

			List<Project> projects = await _projectService.GetAllProjectsByCompanyIdAsync(User.Identity!.GetCompanyId());
			return View(projects);
		}

		[HttpGet]
        [Authorize(Roles = nameof(BTRoles.Admin))]
        public async Task<IActionResult> AssignPM(int? id)
        {
            if (id is null or 0)
            {
                return NotFound();
            }

            Project? project = await _projectService.GetProjectByIdAsync(id.Value, User.Identity!.GetCompanyId());

            if (project is null)
            {
                return NotFound();
            }

            List<BTUser> projectManagers = await _rolesService.GetUsersInRoleAsync(nameof(BTRoles.ProjectManager), User.Identity!.GetCompanyId());
            BTUser? currentPM = await _projectService.GetProjectManagerAsync(id.Value, User.Identity!.GetCompanyId());

            AssignPMViewModel viewModel = new AssignPMViewModel()
            {
                Project = project,
                PMId = currentPM?.Id,
                PMList = new SelectList(projectManagers, "Id", "FullName", currentPM?.Id)
                                  
            };

            return View(viewModel);
        }

        [HttpPost]
        [Authorize(Roles = nameof(BTRoles.Admin))]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AssignPM(AssignPMViewModel assignPMViewModel)
        {
            if (assignPMViewModel.Project?.Id is not null)
            {
                //if unassigned is selected, remove the PM
                if(string.IsNullOrEmpty(assignPMViewModel.PMId))
                {
                    await _projectService.RemoveProjectManagerAsync(assignPMViewModel.Project.Id, User.Identity!.GetCompanyId());
                }
                else  //else, add project manager
                {
                   
                    await _projectService.AddProjectManagerAsync(assignPMViewModel.PMId, assignPMViewModel.Project.Id, User.Identity!.GetCompanyId());
                }

                return RedirectToAction(nameof(Details), new {id = assignPMViewModel.Project!.Id});
            }

            return BadRequest();
        }


        // GET: Projects/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Projects == null)
            {
                return NotFound();
            }

            int companyId = User.Identity!.GetCompanyId();          

            Project? project = await _projectService.GetProjectByIdAsync(id.Value, companyId);

            if (project == null)
            {
                return NotFound();
            }

            return View(project);
        }


        // GET: Projects/Create
        [HttpGet]
        [Authorize(Roles = $"{nameof(BTRoles.Admin)}, {nameof(BTRoles.ProjectManager)}")]
        public async Task<IActionResult> Create()
        {
            List<ProjectPriority> priorities = await _projectService.GetProjectPrioritiesAsync();
            ViewData["ProjectPriorityId"] = new SelectList(priorities, "Id", "Name");

            Project project = new();
            return View(project);
        }


        // POST: Projects/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = $"{nameof(BTRoles.Admin)}, {nameof(BTRoles.ProjectManager)}")] //using Enums class
        public async Task<IActionResult> Create([Bind("Name,Description,StartDate,EndDate,ProjectPriorityId,ImageFormFile")] Project newProject)
        {
            ModelState.Remove("CompanyId");
            if (ModelState.IsValid)
            {
                BTUser? user = await _userManager.GetUserAsync(User);
                int companyId = User.Identity!.GetCompanyId();
				newProject.CompanyId = companyId;

				//Dates
				newProject.Created = DateTime.SpecifyKind(DateTime.Now, DateTimeKind.Utc);
				newProject.StartDate = DateTime.SpecifyKind(newProject.StartDate, DateTimeKind.Utc);
				newProject.EndDate = DateTime.SpecifyKind(newProject.EndDate, DateTimeKind.Utc);

                //Images   
                if (newProject.ImageFormFile != null)
                {
					newProject.ImageFileData = await _fileService.ConvertFileToByteArrayAsync(newProject.ImageFormFile);
                    newProject.ImageFileType = newProject.ImageFormFile.ContentType;
                }

                //If user has role of project manager, add user
                if (User.IsInRole(nameof(BTRoles.ProjectManager)))
                {
					newProject.Members.Add(user);
                }

                await _projectService.AddProjectAsync(newProject);
                return RedirectToAction(nameof(Index));
            }

            List<ProjectPriority> priorities = await _projectService.GetProjectPrioritiesAsync();
            ViewData["ProjectPriorityId"] = new SelectList(priorities, "Id", "Name");

            return View(newProject);
        }


        // GET: Projects/Edit/5
        [HttpGet]
        [Authorize(Roles = $"{nameof(BTRoles.Admin)}, {nameof(BTRoles.ProjectManager)}")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Projects == null)
            {
                return NotFound();
            }

            int companyId = User.Identity!.GetCompanyId();
            Project? project = await _projectService.GetProjectByIdAsync(id.Value, companyId);

            if (project == null)
            {
                return NotFound();
            }

            List<ProjectPriority> priorities = await _projectService.GetProjectPrioritiesAsync();

            ViewData["ProjectPriorityId"] = new SelectList(priorities, "Id", "Name");
            return View(project);
        }

        // POST: Projects/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = $"{nameof(BTRoles.Admin)}, {nameof(BTRoles.ProjectManager)}")]
        public async Task<IActionResult> Edit(int id, [Bind("Id,CompanyId,Name,Description,Created,StartDate,EndDate,ProjectPriorityId,ImageFileData,ImageFileType,ImageFormFile,Archived")] Project project)
        {
            if (id != project.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    //Images
                    if (project.ImageFormFile != null)
                    {
                        project.ImageFileData = await _fileService.ConvertFileToByteArrayAsync(project.ImageFormFile);
                        project.ImageFileType = project.ImageFormFile.ContentType;
                    }

                    //Dates
                    project.Created = DateTime.SpecifyKind(DateTime.Now, DateTimeKind.Utc);
                    project.StartDate = DateTime.SpecifyKind(project.StartDate, DateTimeKind.Utc);
                    project.EndDate = DateTime.SpecifyKind(project.EndDate, DateTimeKind.Utc);

                    await _projectService.UpdateProjectAsync(project, User.Identity!.GetCompanyId());
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProjectExists(project.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }

Views/Projects/Archive.cshtml
@model TheIssueTracker.Models.Project

@{
    ViewData["Title"] = "Archive";
}

<h1>Archive</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Project</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Created)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Created)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.StartDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.StartDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EndDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EndDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ImageFileData)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ImageFileData)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ImageFileType)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ImageFileType)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Archived)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Archived)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Company)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Company.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ProjectPriority)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ProjectPriority.Id)
        </dd>
    </dl>
    
    <form asp-action="Archive">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Archive" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/Projects/ArchivedProjects.cshtml
@model IEnumerable<TheIssueTracker.Models.Project>

@using TheIssueTracker.Models.Enums;
@using TheIssueTracker.Services.Interfaces;
@inject IBTFileService _FileService
@inject IBTProjectService _ProjectService;
@inject IBTRolesService _RolesService;

@{
	ViewData["Title"] = "Archived Projects";
}

<div class="container-fluid">
	<div class="row">
		<h2 class="m-t-0 h3"><b>Archived Projects </b></h2>
	</div>
	<div class="row">
		@foreach (Project project in Model)
		{
			<div class="col-xl-4">
				<div class="card" style="max-width: 30rem">
					<div class="card-header">
						<div class="row">
							<div class="col">
								<h5 style="color:darkred">
									@if ((await _ProjectService.GetProjectManagerAsync(project.Id, project.CompanyId)) == null)
									{
										<div class="row row-cols-2">
											<div class="col d-flex align-items-center" style="color:darkgray">Archived</div>
											<div class="col text-end"><a asp-action="Restore" asp-controller="Projects" asp-route-id="@project.Id" class="btn btn-soft-success .width-xl rounded-pill">Restore</a></div>
										</div>
									}
									else
									{
										@await _ProjectService.GetProjectManagerAsync(project.Id, project.CompanyId)
										;
										<h6 class="text-muted">Project Manager</h6>
									}
								</h5>
							</div>
						</div>

					</div>
					<div class="card-body">
						<div class="text-center">
							<span class="text-muted">Priority Level: </span> @if (project.ProjectPriority!.Name == "Urgent")
							{
								<h5 style="color:firebrick">Urgent</h5>
							}
							else if (project.ProjectPriority!.Name == "High")
							{
								<h5 style="color:orangered">High</h5>

							}
							else if (project.ProjectPriority!.Name == "Medium")
							{
								<h5 style="color:darkslateblue">Medium</h5>
							}
							else if (project.ProjectPriority!.Name == "Low")
							{
								<h5 style="color:forestgreen">Low</h5>
							}
						</div>
						<div><a asp-controller="Projects" asp-action="Details" asp-route-id="@project.Id"><h5 class="card-title text-center">@project.Name</h5></a></div>
						<div class="text-truncate">
							<a asp-controller="Projects" asp-action="Details" asp-route-id="@project.Id"><p class="text-center">@project.Description</p></a>
						</div>
					</div>
					<div class="card-footer">
						<div class="row row-cols-2">
							<div class="col">
								Developers:
							</div>
							<div class="col">
								Submitters:
							</div>
						</div>
					</div>
				</div>
			</div>
		}
	</div>
</div>

Views/Projects/AssignPM.cshtml
@model TheIssueTracker.Models.ViewModels.AssignPMViewModel

@{
    ViewData["Title"] = "Assign Project Manager";
}
<div class="d-flex justify-content-center mt-5 flex-column align-items-center">
    <h3 class="my-5">Assign Project Manager</h3>
    <div class="card">
        <div class="card-header">
            <div class="card-title">@Model.Project!.Name</div>
        </div>
        <div class="card-body">
            <form asp-action="AssignPM" asp-controller="Projects" method="post" class="d-flex flex-column">
                <input type="hidden" asp-for="Project!.Id" />
                <select asp-items="Model.PMList" asp-for="PMId">
                    <option value="">Unassigned</option>
                </select>
                <button type="submit" class="btn btn-primary my-3">Save</button>

                <a asp-action="Details" asp-route-id="@Model.Project!.Id" class="btn btn-secondary">Cancel</a>
            </form>
        </div>
    </div>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Views/Projects/AssignProjectMembers.cshtml
@model TheIssueTracker.Models.ViewModels.AssignProjectMembersViewModel

@{
    ViewData["Title"] = "Edit Members";
}

<div class="d-flex justify-content-center mt-5 flex-column align-items-center">
    <h3 class="my-5">Edit Members</h3>
    <h5>@Model.Project!.Name</h5>
    <div class="row row-cols-2">
        <div class="col">
            <div class="card">
                <div class="card-header">
                    <div class="card-title">Add Members</div>
                </div>
                <div class="card-body">
                    <form asp-action="AssignProjectMembers" method="post" class="d-flex flex-column">
                        <input type="hidden" asp-for="Project!.Id" />
                        <select asp-items="Model.UnassignedList" asp-for="MemberId">
                            <option value="">Unassigned</option>
                        </select>
                        <button type="submit" class="btn btn-success my-3">Add</button>
                    </form>
                </div>
            </div>
        </div>
        <div class="col">
            <div class="card">
                <div class="card-header">
                    <div class="card-title">Remove Members</div>
                </div>
                <div class="card-body">
                    <form asp-action="AssignProjectMembers" method="post" class="d-flex flex-column">
                        <input type="hidden" asp-for="Project!.Id" />
                        <select asp-items="Model.CurrentList" asp-for="MemberId">
                            <option value="">Current Members</option>
                        </select>
                        <button type="submit" class="btn btn-warning my-3">Remove</button>

                    </form>
                </div>
            </div>
        </div>
        
    </div>
    <a asp-action="Details" asp-route-id="@Model.Project!.Id" class="btn btn-soft-secondary d-flex justify-content-center">Go back to Project Details</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Views/Projects/Details.cshtml
@using TheIssueTracker.Models.Enums;
@using TheIssueTracker.Services.Interfaces;
@using Microsoft.AspNetCore.Identity;
@model TheIssueTracker.Models.Project

@inject IBTRolesService _rolesService
@inject IBTProjectService _projectService;
@inject IBTFileService _fileService;
@inject UserManager<BTUser> UserManager;


@{
	ViewData["Title"] = "Details";
	
}


<div class="p-3 d-flex flex-column">

	<div class="row">
		<h1 class="mb-2">Project: @Model.Name</h1>
		<div class="col-lg-7">
			<div class="card">
				<div class="card-body">
					<ul class="nav nav-pills navtab-bg nav-justified">
						<li class="nav-item">
							<a href="#home1" data-bs-toggle="tab" aria-expanded="false" class="nav-link active">
								Project Details
							</a>
						</li>
						<li class="nav-item">
							<a href="#messages1" data-bs-toggle="tab" aria-expanded="false" class="nav-link">
								Project Members
							</a>
						</li>
					</ul>
					<div class="tab-content">
						<div class="tab-pane show active" id="home1">
							<div class="col-12">
								<div class="card">
									<div class="card-header d-flex">
										@* PROJECT'S STATUS *@

										@if (Model.Archived)
										{
											<h5 class="badge bg-secondary">Archived</h5>
										}
										else if (DateTime.UtcNow.Date > DateTime.SpecifyKind(Model.EndDate, DateTimeKind.Utc).Date)
										{
											<h5 class="badge bg-danger">Overdue</h5>
										}
										else
										{
											<h5 class="badge bg-info">In Progress</h5>
										}

										@* ONLY SHOW THESE BUTTONS IF THEY'RE ALLOWED TO DO THESE ACTIONS *@
										@if (User.IsInRole("Admin") || User.IsInRole("Project Manager"))
										{
											<div class="ms-auto">
												<a class="btn btn-sm btn-soft-success" asp-controller="Projects" asp-action="Edit" asp-route-id="@Model.Id">Edit</a>
												<a class="btn btn-sm btn-soft-secondary" asp-controller="Projects" asp-action="Archive" asp-route-id="@Model.Id">Archive</a>
											</div>
										}
									</div>
									<div class="card-body">
										@* PROJECT NAME GOES HERE *@
										<h5 class="card-title">@Model.Name</h5>
										<h6 class="card-subtitle mb-4 text-muted">@Model.StartDate.Date.ToString("MM.dd.yyyy")<span> to </span>@Model.EndDate.Date.ToString("MM.dd.yyyy")</h6>
										<p class="card-text">
											@* PROJECT DESCRIPTION GOES HERE *@
											@Model.Description
										</p>
									</div>
									<div class="card-footer fw-bold lead d-flex">
										 
										<h5>Project Manager: </h5>
										<br>
										@if ((await _projectService.GetProjectManagerAsync(Model.Id, Model.CompanyId)) is null)
										{
											<br>
											<h5 style="text-muted">Unassigned</h5>
										}
										else
										{
											<br>
											<h5>@((await _projectService.GetProjectManagerAsync(Model.Id, Model.CompanyId))!.FirstName)</h5>
										}
											
										@if (User.IsInRole("Admin") && (await _projectService.GetProjectManagerAsync(Model.Id, Model.CompanyId) is not null))
										{
											<div class="ms-auto">
												<div class="d-flex flex-column align-items-stretch align-items-lg-start">
													<a asp-action="AssignPM" asp-controller="Projects" asp-route-id="@Model.Id" class="btn btn-soft-info width-lg m-1 ">
														Change PM
													</a>
												</div>
											</div>
										} 
										else
										{
											<div class="ms-auto">
												<div class="d-flex flex-column align-items-stretch align-items-lg-start">
													<a asp-action="AssignPM" asp-controller="Projects" asp-route-id="@Model.Id" class="btn btn-soft-info width-lg m-1 ">
														Assign PM
													</a>
												</div>
											</div>
										}

									</div>
									@* Only show the "manage project members" button if they're allowed to assign members to this project *@
								
								</div>
							</div>
						</div>
						<div class="tab-pane" id="messages1">
							<div class="col-12">
								<div class="row">
									<div class="col-12 col-lg-6">
										<div class="card h-100">
											@* DISPLAY LIST OF DEVELOPERS ON PROJECT *@
											<div class="card-header">
												Developers
											</div>
											<div class="card-body">
												<ul style="list-style-type: none">
													@foreach (BTUser user in (await _projectService.GetProjectMembersByRoleAsync(Model.Id, nameof(BTRoles.Developer), Model.CompanyId)))
													{
														<li>
														<a href="#" class="avatar-group-item" data-bs-toggle="tooltip" data-bs-placement="top" title="@user.FullName">
															<img src="@_fileService.ConvertByteArrayToFile(user!.ImageFileData,user!.ImageFileType,DefaultImage.BTUserImage)" class="rounded-circle avatar-sm" alt="friend" />
														</a>
														<span>@user.FullName</span>
														</li>
													}
												</ul>
											</div>
										</div>
									</div>
									<div class="col-8 col-lg-6">
										<div class="card h-100">
											@* DISPLAY LIST OF SUBMITTERS ON PROJECT *@
											<div class="card-header">
												Submitters
											</div>
											<div class="card-body">
												<ul style="list-style-type: none">
													@foreach (BTUser user in (await _projectService.GetProjectMembersByRoleAsync(Model.Id, nameof(BTRoles.Submitter), Model.CompanyId)))
													{
														<li>
														<a href="#" class="avatar-group-item" data-bs-toggle="tooltip" data-bs-placement="top" title="@user.FullName">
															<img src="@_fileService.ConvertByteArrayToFile(user!.ImageFileData,user!.ImageFileType,DefaultImage.BTUserImage)" class="rounded-circle avatar-sm" alt="friend" />
														</a>
														<span>@user.FullName</span>
														</li>
													}
												</ul>
											</div>
										</div>
									</div>
									@if ((User.IsInRole("Admin") || User.IsInRole("Project Manager")))
									{
										<div class="col-4 p-2">
											<div class="d-flex flex-column align-items-stretch align-items-lg-start">
												<a asp-action="AssignProjectMembers" asp-controller="Projects" asp-route-id="@Model.Id" class="btn btn-soft-info width-lg m-1 ">
													Manage Project Members
												</a>
											</div>
										</div>
									}
								</div>
							</div>
						</div>
					</div>
				</div>				
			</div> <!-- end card-->
		</div>
		<div class="col-lg-5">
			<h1 class="header-title mb-4">Tickets of This Project</h1>
			<div class="table-responsive mt-4">
				<table class="table table-hover table-bordered text-center no-wrap" id="datatable">
					<thead>
						<tr>
							<th><h5>&nbsp;</h5></th>
							<th><h5>Title</h5></th>
						</tr>
					</thead>
					@foreach (Ticket ticket in Model.Tickets)
					{
						<tbody>
							<tr>
								<td>
									<a class="btn btn-sm btn-soft-info" asp-controller="Tickets" asp-action="Details" asp-route-id="@ticket.Id">Details</a>
									@if (User.IsInRole("Admin") || (User.IsInRole("ProjectManager")) || (User.IsInRole("Developer")))
									{
									
									<a class="btn btn-sm btn-soft-success" asp-controller="Tickets" asp-action="Edit" asp-route-id="@ticket.Id">Edit</a>
									}
								</td>
								<td>@ticket.Title</td>

							</tr>
						</tbody>
					}
				</table>
			</div>
		</div>

		
	</div>

</div>
<div class="mt-5 ms-auto">
	<a asp-action="Index" class="btn btn-secondary">Back to List</a>
</div>

@*<div class="card mb-1">
	<div class="card-header" id="headingOne">
		<h5 class="m-0">
			<a class="text-dark" data-bs-toggle="collapse" href="#collapseOne" aria-expanded="true">				
				What is Vakal text here?
			</a>
		</h5>
	</div>

	<div id="collapseOne" class="collapse show" aria-labelledby="headingOne" data-bs-parent="#accordion">
		<div class="card-body">
			Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute,
			non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod. Brunch 3 wolf moon
			tempor, sunt aliqua put a bird on it squid single-origin coffee nulla assumenda shoreditch et. Nihil
			anim keffiyeh helvetica, craft beer labore wes anderson cred nesciunt sapiente ea proident. Ad vegan
			excepteur butcher vice lomo. Leggings occaecat craft beer farm-to-table, raw denim aesthetic synth nesciunt
			you probably haven't heard of them accusamus labore sustainable VHS.
		</div>
	</div>
</div>*@


@section Scripts{
	<script>
		$('#datatable').DataTable();
	</script>
}