Models/Invite.cs
using System.ComponentModel.DataAnnotations;

namespace TheIssueTracker.Models
{
    public class Invite
    {
        public int Id { get; set; }

        [DataType(DataType.DateTime)]
        [Display(Name = "Invite Date")]
        public DateTime InviteDate { get; set; }

        [DataType(DataType.DateTime)]
        [Display(Name = "Join Date")]
        public DateTime? JoinDate { get; set; }

        public Guid CompanyToken { get; set; }

        public int CompanyId { get; set; }
        public int? ProjectId { get; set; }

        [Required]
        public string? InvitorId { get; set; }

        public string? InviteeId { get; set; }

        [Required]
        [Display(Name = "Invitee Email")]
        [DataType(DataType.EmailAddress)]
        public string? InviteeEmail { get; set; }

        [Required]
        [Display(Name = "Invitee First Name")]
        [StringLength(50, ErrorMessage = "The {0} must be at least {2} and max {1} characters long.", MinimumLength = 2)]
        public string? InviteeFirstName { get; set; }


        [Required]
        [Display(Name = "Invitee Last Name")]
        [StringLength(50, ErrorMessage = "The {0} must be at least {2} and max {1} characters long.", MinimumLength = 2)]
        public string? InviteeLastName { get; set; }

        public string? Message { get; set; }

        public bool IsValid { get; set; }


        //Navigation Properties
        public virtual Company? Company { get; set; }
        public virtual Project? Project { get; set; }

        public virtual BTUser? Invitor { get; set; }
        public virtual BTUser? Invitee { get; set; }
    }
}

Controllers/CompanyController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using TheIssueTracker.Data;
using TheIssueTracker.Extensions;
using TheIssueTracker.Models;
using TheIssueTracker.Models.Enums;
using TheIssueTracker.Models.ViewModels;
using TheIssueTracker.Services;
using TheIssueTracker.Services.Interfaces;

namespace TheIssueTracker.Controllers
{
    [Authorize]
    public class CompanyController : Controller
    {
        private readonly IBTCompanyService _companyService;
		private readonly IBTRolesService _rolesService;
		private readonly UserManager<BTUser> _userManager;

        public CompanyController(IBTCompanyService companyService, IBTRolesService rolesService, UserManager<BTUser> userManager)
        {
            _companyService = companyService;
			_rolesService = rolesService;
			_userManager = userManager;
        }

        // GET: Companies/Details/5
        public async Task<IActionResult> Index()
        {
            int id = User.Identity!.GetCompanyId();

            var company = await _companyService.GetCompanyInfoAsync(id);                ;
            if (company == null)
            {
                return NotFound();
            }

            return View(company);
        }

		[HttpGet]
		[Authorize(Roles = nameof(BTRoles.Admin))]
		public async Task<IActionResult> ManageUserRoles()
		{
			List<BTUser> members = await _companyService.GetCompanyMembersAsync(User.Identity!.GetCompanyId());
			List<IdentityRole> roles = await _rolesService.GetRolesAsync();
			List<ManageUserRolesViewModel> model = new();

			foreach (BTUser member in members)
			{
				//if the member id is not me && not a demo user
				if (member.Id != _userManager.GetUserId(User) && !await _rolesService.IsUserInRole(member, nameof(BTRoles.DemoUser)))
				{
					IEnumerable<string> userRoles = await _rolesService.GetUserRolesAsync(member);

					ManageUserRolesViewModel viewModel = new()
					{
						Roles = new SelectList(roles, "Name", "Name", userRoles.FirstOrDefault()),
						User = member,
					};

					model.Add(viewModel);
				}
			}

			return View(model);
		}

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = nameof(BTRoles.Admin))]
        public async Task<IActionResult> ManageUserRoles(ManageUserRolesViewModel viewModel)
        {
            string? selectedRole = viewModel.SelectedRole;
            string? userId = viewModel.User?.Id;

            if (string.IsNullOrEmpty(userId) || string.IsNullOrEmpty(selectedRole))
            {
                return NotFound();
            }

            BTUser? user = await _userManager.FindByIdAsync(userId);
            if (user == null || await _rolesService.IsUserInRole(user, nameof(BTRoles.DemoUser)) || user.CompanyId != User.Identity!.GetCompanyId())
            {
                return NotFound();
            }

            IEnumerable<string> currentRoles = await _rolesService.GetUserRolesAsync(user);

            if (await _rolesService.RemoveUserFromRolesAsync(user, currentRoles))
            {
                await _rolesService.AddUserToRoleAsync(user, selectedRole);
            }

            return RedirectToAction(nameof(ManageUserRoles));
        }
    }
}

Controllers/InvitesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.DataProtection;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.UI.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using TheIssueTracker.Data;
using TheIssueTracker.Extensions;
using TheIssueTracker.Models;
using TheIssueTracker.Models.Enums;
using TheIssueTracker.Services.Interfaces;

namespace TheIssueTracker.Controllers
{
    [Authorize(Roles = nameof(BTRoles.Admin))]
    public class InvitesController : Controller
	{
		private readonly IBTInviteService _inviteService;
		private readonly IBTProjectService _projectService;
		private readonly IBTCompanyService _companyService;
		private readonly IEmailSender _emailSender;
		private readonly UserManager<BTUser> _userManager;
		private readonly IDataProtector _protector;
		private readonly string _protectorPurpose;

		public InvitesController(IBTInviteService inviteService,
								 IBTProjectService projectService,
								 IBTCompanyService companyService,
								 IEmailSender emailSender,
								 UserManager<BTUser> userManager,
								 IDataProtectionProvider protectionProvider)
		{
			_inviteService = inviteService;
			_projectService = projectService;
			_companyService = companyService;
			_emailSender = emailSender;
			_userManager = userManager;

			_protectorPurpose = "iScribe2023!!!";
			_protector = protectionProvider.CreateProtector(_protectorPurpose);
		}


		// GET: Invites/Create	
        public async Task<IActionResult> Create()
		{
            int companyId = User.Identity!.GetCompanyId();

            List<Project> companyProjects = await _projectService.GetAllProjectsByCompanyIdAsync(User.Identity!.GetCompanyId());

			ViewData["ProjectId"] = new SelectList(companyProjects, "Id", "Name");

			return View();
		}

		// POST: Invites/Create
		// To protect from overposting attacks, enable the specific properties you want to bind to.
		// For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
		[HttpPost]
		[ValidateAntiForgeryToken]       
        public async Task<IActionResult> Create([Bind("ProjectId,InviteeEmail,InviteeFirstName,InviteeLastName,Message")] Invite invite)
		{
			int companyId = User.Identity!.GetCompanyId();

			ModelState.Remove("InvitorId");
			if (ModelState.IsValid)
			{
				try
				{
					//assign invite values as we dont want user to be setting these values
					Guid guid = Guid.NewGuid();

					invite.CompanyToken = guid;
					invite.CompanyId = companyId;
					invite.InviteDate = DateTime.UtcNow;
					invite.InvitorId = _userManager.GetUserId(User);
					invite.IsValid = true;

					//save it
					await _inviteService.AddNewInviteAsync(invite);

					//encrypting our top secret invite info so we cannot just guess the url of the invite.
					//token is unique and hard to guess
					string token = _protector.Protect(guid.ToString());
					string email = _protector.Protect(invite.InviteeEmail!);
					string company = _protector.Protect(companyId.ToString());

					//magic url
					string? callbackUrl = Url.Action("ProcessInvite", "Invites", new { token, email, company }, Request.Scheme);

					//send the invite email
					string body = $@"<h4> You've been invited to join the bug tracker!</h4> <br/>
                                        {invite.Message}<br/><br/> 
                                        <a href=""{callbackUrl}"">Click here</a> to join our team.";

					string subject = $@"You've been invited to join The Issue Tracker";

					await _emailSender.SendEmailAsync(invite.InviteeEmail!, subject, body);

					return RedirectToAction("Index", "Home", new { SwalMessage = "Invite Sent!" });
				}
				catch (Exception)

				{

					throw;
				}
			}

			//if not valid, return the invite view and repop the form from view page
			List<Project> companyProjects = await _projectService.GetAllProjectsByCompanyIdAsync(User.Identity!.GetCompanyId());
			ViewData["ProjectId"] = new SelectList(companyProjects, "Id", "Name");
			return View(invite);
		}

        [AllowAnonymous]
        public async Task<IActionResult> ProcessInvite(string? token, string? email, string? company)
		{
			//if any of the parameters are null return not found
			if (string.IsNullOrEmpty(token) || string.IsNullOrEmpty(email) || string.IsNullOrEmpty(company))
			{
				return NotFound();
			}

			//we need to decrypt these previously encrypted values
			Guid companyToken = Guid.Parse(_protector.Unprotect(token));
			string inviteeEmail = _protector.Unprotect(email);
			int companyId = int.Parse(_protector.Unprotect(company));

			try
			{
				//use getinviteasync overloaded method with diff parameters
				Invite? invite = await _inviteService.GetInviteAsync(companyToken, inviteeEmail, companyId);

				if (invite is null)
				{
					return NotFound();
				}

				return View(invite);
			}
			catch (Exception)
			{

				throw;
			}

			
		}
	}
}

Views/Invites/Create.cshtml
@model TheIssueTracker.Models.Invite

@{
    ViewData["Title"] = "Create";
}
<h1 class="text-center">Create</h1>
<h4 class="text-center">Invite</h4>
<hr />
<div class="col-lg-12 col-md-12 d-flex justify-content-center">
    <div class="card custom-card">
        <div class="card-body">
            <div>
                <p class="text-muted text-center card-sub-title">Invite a new user to join!</p>
            </div>
            <form asp-action="Create">
                <div class="row row-xs align-items-center mg-b-20 p-2">
                    <div class="col-md-4">
                        <label class="mg-b-0">Email</label>
                    </div>
                    <div class="col-md-8 mg-t-5 mg-md-t-0">
                        <input type="email" asp-for="InviteeEmail" class="form-control" placeholder="Enter email">
                    </div>
                </div>
                <div class="row row-xs align-items-center mg-b-20 p-2">
                    <div class="col-md-4">
                        <label class="mg-b-0">Firstname</label>
                    </div>
                    <div class="col-md-8 mg-t-5 mg-md-t-0">
                        <input type="text" asp-for="InviteeFirstName" class="form-control" placeholder="Enter first name">
                    </div>
                </div>
                <div class="row row-xs align-items-center mg-b-20 p-2">
                    <div class="col-md-4">
                        <label class="mg-b-0">Lastname</label>
                    </div>
                    <div class="col-md-8 mg-t-5 mg-md-t-0">
                        <input type="text" asp-for="InviteeLastName" class="form-control" placeholder="Enter last name">
                    </div>
                </div>
                <div class="row row-xs align-items-center mg-b-20 p-2">
                    <div class="col-md-4">
                        <label class="mg-b-0">Select Project</label>
                    </div>
                    <div class="col-md-8 mg-t-5 mg-md-t-0">
                        <select class="form-control" asp-for="ProjectId" asp-items="@ViewBag.ProjectId">
                            <option value="">Select Project</option>
                        </select>
                    </div>
                </div>
                <div class="row row-xs align-items-center mg-b-20 p-2">
                    <div class="col-md-4">
                        <label class="mg-b-0">Message</label>
                    </div>
                    <div class="col-md-8 mg-t-5 mg-md-t-0">
                        <textarea asp-for="Message" multiple="multiple" class="form-control"></textarea>
                    </div>
                </div>
                <div class="form-group row justify-content-end mb-0 p-2">
                    <div class="col-md-8 pl-md-2">
                        <input type="submit" class="btn ripple btn-primary pd-x-30 mg-r-5" value="Send Invite" />
                        <button class="btn ripple btn-secondary pd-x-30">Cancel</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
<div class="text-center">
    <a asp-action="Index" asp-controller="Company" >Back to List</a>
</div>
@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Views/Invites/ProcessInvite.cshtml
@model TheIssueTracker.Models.Invite
@using TheIssueTracker.Services.Interfaces
@using TheIssueTracker.Services

@{
    ViewData["Title"] = "Process Invite";    
}
<div class="panel card-sign">
    <div class="card-title mt-3 text-center">
        <h2 class="title text-uppercase font-weight-bold m-0"> Invite</h2>
    </div>
    <div class="header">
        <h3>
            <span class="clearfix title">
                <span class="number">Welcome</span><br />
                <span>@Model.InviteeFirstName @Model.InviteeLastName!</span> <br>
            </span>
        </h3>
        <h5><span>Company Name: @Model.Company!.Name </span></h5>
    </div>
    <div class="card-body">
        <p>
            @Model.Invitor!.FullName has invited you to collaborate on the @Model.Project!.Name project.
            <br /><br /> Click the "JOIN" button below to register with the company and begin entering tickets.
        </p>
        <a class="btn btn-primary btn-lg btn-block" 
            asp-area="Identity" 
            asp-page="/Account/RegisterByInvite" 
            asp-route-token="@Model.CompanyToken.ToString()" 
            asp-route-companyId="@Model.CompanyId" 
            asp-route-id="@Model.Id">
                <i class="bi bi-box-arrow-in-right"></i> <span>JOIN</span></a>
    </div>
</div>